version: '3.8'

services:
  python_service:
    build: ./python_service
    ports:
      - "8000:8000"
    volumes:
      - ./python_service:/app
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PYTHON_SERVICE_URL=http://python_service:8000
    depends_on:
      - python_service

  frontend:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend